-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module RedHouse.Object.Item exposing (description, id, specs, tagLine, url)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import RedHouse.InputObject
import RedHouse.Interface
import RedHouse.Object
import RedHouse.Scalar
import RedHouse.ScalarCodecs
import RedHouse.Union


{-| Item ID
-}
id : SelectionSet String RedHouse.Object.Item
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| Item tag line.
-}
tagLine : SelectionSet String RedHouse.Object.Item
tagLine =
    Object.selectionForField "String" "tagLine" [] Decode.string


{-| Image url
-}
url : SelectionSet (Maybe String) RedHouse.Object.Item
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


description : SelectionSet (Maybe String) RedHouse.Object.Item
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


specs : SelectionSet (Maybe (List String)) RedHouse.Object.Item
specs =
    Object.selectionForField "(Maybe (List String))" "specs" [] (Decode.string |> Decode.list |> Decode.nullable)
